apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-b
  namespace: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-b
  template:
    metadata:
      labels:
        app: microservice-b
    spec:
      containers:
        - name: microservice-b
          image: microservice-b:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-b-service
  namespace: edge
spec:
  selector:
    app: microservice-b
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP
